### PR TITLE
Fixed broken links in README

### LINKED ISSUE #1102: README.md broken links
#### Describe the bug
Some of the links in the README.md are broken

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Fixes #1102

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
Unable to get past the following screen:

image

Not working in Chrome and Firefox (tried without add-ons/extensions as well)

**Comment by Ecco** [comment]
Hi @gaurav-nelson, thank you for your help !

I have no idea what's wrong with the CLA bot… Anyway, I'm going to close this PR because we're in the process of changing our CI suite and I needed to modify the README anyway.

Thanks though, I'm sorry I couldn't merge your PR!

**Comment by Ecco** [comment]
#1136

**Comment by gaurav-nelson** [comment]
No worries :)

**Pull request closed without merging**
