### PR TITLE
Brightness settings

### PR DESCRIPTION
**Pull request by jperon**
dimBacklightBrightness, idleBeforeDimmingSecs and idleBeforeSuspendMins parameters
with entries in settings menu.
This allows the user to change time before dimming screen or suspending, and to set the level of dimmed brightness.

### CODE REVIEW

**Comment by jperon** [comment]
N. B. : incidentally, fix #902.

**Comment by Ecco** [comment]
Here are a couple screenshots of what this PR adds.

**Main settings menu**
Main menu

**Brightness menu**
Brightness menu

**Comment by Ecco** [comment]
I personally think this is an interesting PR, but I'm not sure wether we should merge it. It adds quite a lot of complexity, and I'm not quite sure which problem this is trying to solve.

As a general rule, we try to add as _few_ settings as possible. Is there a reason one would like to change the delays and the dimmed brightness?

**Comment by adriweb** [comment]
> As a general rule, we try to add as _few_ settings as possible. Is there a reason one would like to change the delays and the dimmed brightness?

I suppose this would make it aligned with other calcs (at least, high-end ones) that provide this kind of tweaking in their settings.
For instance on the TI-Nspire CX:
image

(The brightness itself it done via two keypresses)

**Comment by boricj** [comment]
I think the "Dim" setting is superfluous, as simply subtracting a couple of brightness levels from its normal level when dimming should be enough. Similarly, the "Dim after (s)" setting is probably not that useful too in practice as students should still be able to read out the display when the screen is dimmed, assuming the normal brightness level is properly set in the first place

However, being able to set the delay before going to sleep is a good idea since students in exams might:
* prefer a longer timeout than normal because their calculator keeps turning off after thinking for a bit, especially if they are really stressed out ;
* prefer to dial down both brightness and timeout if they realize they are running out of battery at the worst possible time.

I think it'd be even more useful if the calculator could display the current time (to prevent the lost-track-of-time-because-of-no-visible-clock syndrome in exam), but that's not possible for now.

Now, I know themes support just got shot down, but as long as we have a new settings section, it would really not cost much to rename it from "Brightness" to "Appearance" and add a setting for inverting colors in this menu as a poor man's night mode. Just sayin'.

**Comment by jperon** [comment]
Thank you all for your interest.

I had a request for those settings, not from a student, but from a teacher ; the main issue for him is that the screen gets dimmed too quick, and he doesn't see well with minimal brightness. So, for those who'd have the same expectation, the two "dim" settings would be most important.

Otherwise, I agree with @boricj about the renaming from "Brightness" to "Appearance" and color inverting.

**Comment by boricj** [comment]
The firmware currently sets the brightness level to minimum when dimming the screen. Perhaps reducing the brightness instead (either by a set amount or a percentage of the normal level) would solve that problem. Smartphones don't set their brightness level to minimum when dimming the screen.

**Comment by jperon** [comment]
That's one issue this PR solves. I added a setting for that, because expectations could be different : someone could want to prioritize battery saving while another one would like to see better.

**Comment by quentinguidee** [comment]
Hello @jperon !

Can we reuse this pull request in [Omega](https://github.com/Omega-Numworks/Omega) and add your name in our contributors page ? Thank you :)

**Comment by jperon** [comment]
@quentinguidee For sure you can reuse it, with or without my name.
Thanks !

**Comment by quentinguidee** [comment]
Thank you :) !

**Comment by RedGl0w** [comment]
I'll PR your branch to update with epsilon master today

**Pull request closed without merging**
