### PR TITLE
[ion/device/display] Gamma correction (#609)

### PR DESCRIPTION
**Pull request by claire-savinas**
An attempt to have a better color rendering on the device.

Gamma correction value were calculated by @tvillingett

### CODE REVIEW

**Comment by Ecco** [comment]
Hi! I just gave this a try and this looks a lot *worse* 😄
I tried to take a photo, the result isn't that good, but you get the idea. Left is before, right is with the patch applied. The colors are completely desaturated and washed-out…

img_0759

**Comment by tvillingett** [comment]
Hmm.
Do we have different displays/ or batches perhaps? I could not find the display manufacturer in the data sheets for the Numworks hardware.

I tuned the values a slight bit with the values below:
```c++
  #define ARR_GAMMA_AE_NEW3 0x70,0x5,0x9,0x9,0xB,0x1A,0x30,0x66,0x3D,0x15,0x10,0x10,0x18,0x1F
  SEND_COMMAND(PositiveVoltageGammaControl, ARR_GAMMA_AE_NEW3);
  SEND_COMMAND(NegativeVoltageGammaControl, ARR_GAMMA_AE_NEW3);
```
And the look for me is almost identical with the one you have to the left.
Can we make a dump from the memory of the chip to make sure the default value is what we think it is? What else could be different?

**Comment by tvillingett** [comment]
One difference: I have made my changes to an old branch, with the Swedish translation, but it does not seem to be different in the display init section.

**Comment by Ecco** [comment]
Hi! Thanks for this PR! Unfortunately I'm going to close it because we've already merged something similar with [per-panel gamma calibration](https://github.com/numworks/epsilon/blob/587b5e7a930593c42f7fdbd16bce19b9fe04380e/ion/src/device/shared/drivers/display.cpp#L434).

**Pull request closed without merging**
