### PR TITLE
More friendly french translations

### PR DESCRIPTION
**Pull request by wow0000**
Edit of app/settings/base.fr.i18n with somes "de" to be a bit more friendly
`
SerialNumber = "Numero *de* serie" `
`
UpdatePopUp = "Rappel *de* mise a jour"
`
image

Thanks ! 👍

### CODE REVIEW

**Comment by Ecco** [comment]
Very good suggestion. I think we didn't do this in the first place because we lacked some space (the serial number used to be longer, for example). We'll definitely need to check this. Thanks!

**Comment by matheod** [comment]
Could be nice if the serial number on the workshop could also get the compression so they are both the same (or at least tell us how it's parsed). See #598

**Comment by AlainBusser** [comment]
While you're at it please don't forget issue #215 :wink:

**Comment by LeaNumworks** [comment]
Hi @wow0000,
Sorry for the huge delay to review your PR. I created #1462 with your rebased commit, because I could not push on your repo to change this PR directly, and I will merge that one.
Thanks for your code!

**Pull request closed without merging**
