### PR TITLE
Negative diameter circle turtle support

### PR DESCRIPTION
**Pull request by RedGl0w**
This patch https://github.com/numworks/epsilon/issues/1506

### CODE REVIEW

**Comment by artaxxx** [comment]
Thanks @RedGl0w ! It works great!

**Comment by Ecco** [comment]
One quick remark : aren't we re-inventing `fabs()` here? We were already using the same construct though.

**Comment by RedGl0w** [comment]
> fabs()

**Comment by RedGl0w** [comment]
Sorry misscliclk :/

**Comment by RedGl0w** [comment]
> One quick remark : aren't we re-inventing `fabs()` here? We were already using the same construct though.

If you are talking of
```cpp
(radius > 0 ? 1 : -1)
```
This was already used in the same line, so I thought the same it was, the better it was... If you prefer a cleaner solution, I can change the whole line :smile:

**Pull request merged**
