### PR TITLE
Exam mode upgrade

### PR DESCRIPTION
**Pull request by LeaNumworks**

### CODE REVIEW

**Comment by boricj** [comment]
Wouldn't it be a better idea to store the exam mode inside the RTC backup registers? That wouldn't require odd Flash layouts.

**Comment by M4xi1m3** [comment]
RTC backups registers seems to be cleared on reset on the n0110.

**Comment by EmilieNumworks** [comment]
Hi @boricj,
Unfortunately, this would require the MCU vbat pin to be wired (which is currently not)... Also, RTC works on vbat mode only if clocked by a LSE source, which raises issues about consumption.

**Comment by boricj** [comment]
Oh well, maybe for the next PCB revision then.

**Pull request merged**
