### PR TITLE
[python] Implement get_keys, wait_vblank in kandinsky

### PR DESCRIPTION
**Pull request by boricj**
These functions are already directly provided by kandinsky, might as well expose them to Python. Still a far cry from what we can do (#416), but these functions are essentially free to implement.

### CODE REVIEW

**Comment by boricj** [comment]
I've added blitting and key reading functions, so one can make "real" games on the calculator now (proof: https://workshop.numworks.com/python/jblbeurope/pong).

Drawing performance is disappointing, probably because the framebuffer isn't memory-mapped, but it's usable as long as one doesn't attempt to redraw the entire screen in real time. The only way to achieve good drawing performance would be to "race" the beam by redrawing the entire screen in one go (like GESTE did), but that would be a quite the challenge to do it quickly enough from within MicroPython...

I've moved the Python interrupt key to the Home button. Not sure if that's a welcome change, but two main buttons is better than one and it's less likely someone would exit out of a Python script while trying to hit the OK key.

**Comment by boricj** [comment]
I've added functions for blitting pixels (`get_pixels()`/`set_pixels()`) as well as reading keys (`get_keys()`). Performance is honestly quite terrible for several reasons (lack of memory-mapped buffer, display controller optimized for full-screen bulk updates) and racing the beam like in GESTE from MicroPython would be quite challenging to implement and use... On the upside, there's now everything we need to make real games in Python (proof: https://workshop.numworks.com/python/jblbeurope/pong).

I did change a couple of things, most notably the Python interrupt key for scripts (from Back to Home). On one hand accidentally hitting the Back key instead of the OK key while playing games is bound to infuriate some users and having two main action buttons is better than just one, on the other hand I'm not sure if that's really a good idea...

**Comment by boricj** [comment]
I've updated the PR and the pong code sample to match #925. I also removed everything that isn't needed for that issue, except for key bindings changes in the simulator to make the Python app bearable with the keyboard.

I can't compile/test this on a real device for now, hopefully it'll work on the first try.

**Comment by adriweb** [comment]
fill_rect is now available with 926b96cafbf7176bb39e78d7fa1617f25ddc254f + 8308068b694b397bbcc92ca3552541ec55ffa233

**Comment by boricj** [comment]
@adriweb I noticed. I'm experimenting with tilemapping from Python right now in an attempt to justify a `set_pixels` method (and create games that look a bit better than those from an Atari 2600), but the non-intrusive ways I've tried are extremely non-optimal (MicroPython runs out of memory above 16 8x8 tiles, and that's just the tileset...). Overcoming this would require exposing epsilon's shared data storage as read-only files and adding text+binary record types, but I *highly* doubt the NumWorks team would be interested... Looks like the only thing we'll ever tilemap here will be the character table >_<

**Comment by boricj** [comment]
I've updated the PR and removed what's implemented upstream now. The `get_keys` method returns a set of strings representing the currently pressed keys ; it's both easy to manipulate with set operators and fairly generic.

**Comment by boricj** [comment]
Per #992, removing commit concerning simulator.

**Comment by Ecco** [comment]
Hi @boricj ! Thanks for this PR!

I'm suggesting #1201 , see #925 for explanations.

**Comment by elicolh** [comment]
be careful, up and right are inverted

**Comment by Ecco** [comment]
Indeed, good catch. But this PR has been superseeded by #1201 anyway, so I'm closing this one.

**Pull request closed without merging**
