### PR TITLE
Flatten Icons

### PR DESCRIPTION
**Pull request by sajjaadf**
To make everything look the same. (no gradients in some)

### CODE REVIEW

**Comment by sajjaadf** [comment]
https://travis-ci.org/numworks/epsilon.svg?branch=master

**Comment by sajjaadf** [comment]
HELLO?

**Comment by Ecco** [comment]
Hi @sajjaadf ! Thank you very much for taking your time to share this modification with the community. Unfortunately though, we're not going to merge this pull request as we have no plan to change the user interface's paradigm at the moment.

That being said, your patch should apply cleanly on top of the master branch for a while since we rarely change icons. As a result, you should be able to easily keep using these icons and benefits from commits to the master branch 😄

**Comment by sajjaadf** [comment]
sigh

**Pull request closed without merging**
