### PR TITLE
Added make epsilon_run and make cleanall

### PR DESCRIPTION
**Pull request by RedGl0w**
This patch https://github.com/numworks/epsilon/issues/1231#issuecomment-562140084

### CODE REVIEW

**Comment by EmilieNumworks** [comment]
Hi @RedGl0w, the %_run target should be platform dependent.
See in build/target.device.mak, it's already implemented:

```
.PHONY: %_run
%_run: $(BUILD_DIR)/%.$(EXE)
	$(GDB) -x build/$(PLATFORM)/gdb_script.gdb $<
```

or in build/target.simulator.android.mak or build/target.simulator.ios.mak:

```
.PHONY: %_run
%_run: $(BUILD_DIR)/%.apk
	$(call rule_label,ADB)
	$(Q) adb install $<
```

Your implementation works for windows I believe. On macos, your would want to do something like
`open output/debug/simulator/macos/epsilon.app`.

**Comment by RedGl0w** [comment]
> Hi @RedGl0w, the %_run target should be platform dependent.

That is exactly what I'm trying to not do :trollface: 
Like Ecco said here : https://github.com/numworks/epsilon/issues/1231#issuecomment-562140084, a crossplatform solution to start the simulator could be very usefull. On linux it works well, I'm trying on macos...

**Comment by EmilieNumworks** [comment]
But it won't work on Android, iOS nor on the device?

**Comment by Ecco** [comment]
> That is exactly what I'm trying to not do :trollface:

But that's exactly what's going to **not** work 😄

**Comment by Ecco** [comment]
Also, this PR does two things. Not a big problem, but it'd be much better to open two PRs so we could discuss each feature individually.

**Comment by RedGl0w** [comment]
> Also, this PR does two things. Not a big problem, but it'd be much better to open two PRs so we could discuss each feature individually.

okay, I'll try to do this today

**Pull request closed without merging**
