### PR TITLE
Manually change the color of functions/sequences

### LINKED ISSUE #1247: Manually change the color of functions/sequences
Currently the color of the functions and sequences we plot are random.
I think it would be a good to add the option to  **change the color of the functions** we plot in the function app :) (and also in the sequence app ofc)

- Like for instance if we want to differentiate derivatives from their primitives, it would be easier to differentiate them.

- Or also if you want to create 1 function out of 2/3/... functions (a function defined by parts), then put them both at the same color ;)

- etc.

In direct acces in this menu : 
screenshot (5)
screenshot (6)

Thank you for reading :)

### PR DESCRIPTION
**Pull request by EbbDrop**
Adds a new menu to the function/sequence option-menu to change the color.
Screenshot_from_2020-03-06_01-55-25
Old version see update below!
Fixes #1247 and helps with #931

### CODE REVIEW

**Comment by MixedMatched** [comment]
I would prefer adding a color_view to escher and using gauges as well as presets. That way colors don't have a limited amount. I'll see what I can do later today.

**Comment by EbbDrop** [comment]
I will add a custom color option. But I don't think it is necessary to make a color_view just for functions.

**Comment by MixedMatched** [comment]
How are you going to show what color something is in the preference menu if you can't show color? Are you just going to say "Custom"? And, if we use a color_view, we can create a row (not a column) of small cells that just have colors instead of a list of colored words.

**Comment by EbbDrop** [comment]
Sorry i think i misunderstood you. A color_view seems like a good idee. How would you implement the custom color option?

**Comment by EbbDrop** [comment]
Added a nicer color selector by making a color_view:

It also works with longer names:

**Comment by MixedMatched** [comment]
Wow! That's a very clean implementation. I'm going to see if I can add a clean way for custom colors. If I make one, I'll PR your PR in a few hours.

**Comment by cent20net** [comment]
I love this feature ! Smart and easy to use !

**Comment by EbbDrop** [comment]
@cent20net Thanks :)

**Comment by artaxxx** [comment]
Thanks @EbbDrop , that's interesting :)

I think the list display is better because it's more consistent with the interface of the product. Here are the mockups we worked on to fit the UI:

**Comment by metawops** [comment]
Still no coloring option in Grapher in the current version (18.2.0), right? :-(((

**Comment by Yaya-Cout** [comment]
It's in the 19.0.0 beta version

**Comment by metawops** [comment]
> It's in the 19.0.0 beta version.

Awesome! Unfortunately, can’t install it on my device. Tried several times. Stays at 18.2.0. 🤷‍♂️

**Comment by artaxxx** [comment]
> > It's in the 19.0.0 beta version.
> 
> Awesome! Unfortunately, can’t install it on my device. Tried several times. Stays at 18.2.0. 🤷‍♂️

The beta version is not available for N0100 models for now

**Comment by metawops** [comment]
> > > It's in the 19.0.0 beta version.
> > 
> > 
> > Awesome! Unfortunately, can’t install it on my device. Tried several times. Stays at 18.2.0. 🤷‍♂️
> 
> The beta version is not available for N0100 models for now

Ahhh, thanks for the hint! It‘s very „unfortunate“ that the process seems to finish successfully, though …
4C7D2456-5F7E-4783-9829-AA87DAEC98C3

So, what other models are there? I, indeed, have a N0100 version … 😞

**Pull request closed without merging**
