### PR TITLE
[ion/sdl] Linux support

### PR DESCRIPTION
**Pull request by boricj**
image

This adds support for Linux on the SDL platform, with OpenGL acceleration and software fallback. Build with `PLATFORM=sdl MODEL=linux make`.

There's some trickery for bundling and loading the background JPEG file since ELF files don't have a native mechanism to bundle resources, hopefully the workaround is acceptable.

### CODE REVIEW

**Comment by Ecco** [comment]
Great, thanks!

I see an issue with this PR: it tries really hard to emulate what is done for other platforms, but I'm not sure it makes a lot of sense on Linux. Namely:

* It tries to embed an image decompression library. Definitely something we'd rather avoid as it makes for a large binary. Let's just rely on a system-provided libjpeg.
* It also embeds the JPEG image into the ELF file.

Both of those things make sense on platforms where users are used to downloading standalone binaries. But AFAIK, this is definitely not how things are usually done on Linux.

**Comment by boricj** [comment]
If we rely on a system-provided libjpeg, we might as well rely on a system-provided libsdl too since we'll lose distribution portability anyway. Should I amend the pull request in that way?

The bit about embedding JPEG files into the program however is important: epsilon doesn't have to find files at runtime and can thus be run from anywhere on the file-system, regardless of the current working directory.

**Comment by Ecco** [comment]
> If we rely on a system-provided libjpeg, we might as well rely on a system-provided libsdl too since we'll lose distribution portability anyway.

Actually that's what I thought too. But on a second thought, it might make sense to build libsdl because:

* It allows us to control which SDL version is used
* libjpg is pretty much ubiquitous, so it would make sense to depend on it. It's definitely not the case for libsdl.

>  Should I amend the pull request in that way?

Please don't since it's going to conflict with #1118 anyway.

> The bit about embedding JPEG files into the program however is important: epsilon doesn't have to find files at runtime and can thus be run from anywhere on the file-system, regardless of the current working directory.

Well, that's true. I tried to find some examples to get some "good practices". The only one I found was Blender. They seem to be shipping images as separate files but are depending on some external libraries.

```
$ ldd blender
linux-vdso.so.1 (0x00007fffb2af8000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f83a83d4000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f83a81b7000)
libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f83a7f48000)
libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f83a7cd6000)
libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f83a7996000)
libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f83a7786000)
libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f83a757e000)
libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f83a7378000)
libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f83a716e000)
libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f83a6f6b000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f83a6d67000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f83a69c8000)
/lib64/ld-linux-x86-64.so.2 (0x00005595fad0d000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f83a66c2000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f83a64ab000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f83a6129000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f83a5eff000)
libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f83a5cfc000)
libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f83a5af9000)
libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f83a58f0000)
libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f83a56ee000)
libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f83a54bf000)
libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f83a52ad000)
libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f83a50aa000)
libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f83a4ea8000)
libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f83a4c7e000)
libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f83a4a63000)
libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f83a485e000)
libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f83a464e000)
libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f83a444a000)
libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f83a4242000)
libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f83a402c000)
```

**Comment by Ecco** [comment]
Or we could simply use a static libjpeg build? It's installed by default alongside the dynamic version on [Debian](https://packages.debian.org/buster/amd64/libjpeg62-turbo-dev/filelist).

**Comment by Ecco** [comment]
This is being merged into #1118 . Doing an actual `git-merge` was too much of a trouble so it won't show in the logs unfortunately...

Anyway, thanks @boricj for your help!

**Pull request closed without merging**
