### PR TITLE
Real random with emscripten

### PR DESCRIPTION
**Pull request by RedGl0w**
So we can have **real** random with emscripten

### CODE REVIEW

**Comment by EmilieNumworks** [comment]
`emscripten_random` is implemented using `Math.random()` of javascript standards whereas we used `rand()` of the C++ standard library. I am not familiar with both the implementations, why do you think one is better than the other?
The issue you might have collaterally resolved  is that the seed used for emscripten seems to be always the same... It had been resolved [there](https://github.com/numworks/epsilon/commit/8e725ce328a41482935361b621a74afc784fa4cb) but is broken again. I'll look into it now.

**Comment by RedGl0w** [comment]
> `emscripten_random` is implemented using `Math.random()` of javascript standards whereas we used `rand()` of the C++ standard library. I am not familiar with both the implementations, why do you think one is better than the other?
> The issue you might have collaterally resolved is that the seed used for emscripten seems to be always the same... It had been resolved [there](https://github.com/numworks/epsilon/commit/8e725ce328a41482935361b621a74afc784fa4cb) but is broken again. I'll look into it now.

That was exactly for this reason, but I think using `Math.random()` is better than time for setting the seed. I'll commit that in a few minutes

**Comment by RedGl0w** [comment]
Closed by https://github.com/numworks/epsilon/pull/1517

**Comment by EmilieNumworks** [comment]
The feature is broken on other platforms (ios, android) as well. So we want to fix it for all at once - see #1517.

**Pull request closed without merging**
