### PR TITLE
[python] Add a draw_line function in kandinsky

### PR DESCRIPTION
**Pull request by Lauryy06**
Like #1511, but the function is in the toolbox, and there isn't any conflict.

### CODE REVIEW

**Comment by cent20net** [comment]
[FR] Excellente initiative. Si vous pouviez aussi ajouter une fonction native pout tracer des cercles, cela serait parfait.

[EN] Excellent initiative. If you could also add a native function to draw circles, that would be great.

**Comment by RedGl0w** [comment]
> [FR] Excellente initiative. Si vous pouviez aussi ajouter une fonction native pout tracer des cercles, cela serait parfait.
> 
> [EN] Excellent initiative. If you could also add a native function to draw circles, that would be great.

There's currrently in kandinsky (not the module) no circle primitive (or arc). But this could be nice

**Comment by Lauryy06** [comment]
I'm working on it. I'm rather busy for the moment, but I've already implemented a function to draw the outline of a circle.

**Comment by Lauryy06** [comment]
I will reopen this pull request with new features soon.

**Comment by cent20net** [comment]
Why did you closed it ?

**Comment by Lauryy06** [comment]
I closed it because I opened another one with more functions (including draw_line), and because I had some problems with my commits, as shown by the duplicates.

**Pull request closed without merging**
