### PR TITLE
[apps/code] Script size 

### PR DESCRIPTION
**Pull request by RedGl0w**
This patch https://github.com/numworks/epsilon/issues/1290

## The result (in red and with another button)
image
By hitting the ok button you get that :
image

## Todo :
- [x] Add the translations

Note : this is a reopen of https://github.com/numworks/epsilon/pull/1347

### CODE REVIEW

**Comment by artaxxx** [comment]
Thanks @RedGl0w! I'm still wondering if it's the best place to display the size of the script but I flashed a device with your PR and I noticed some little things:
* as the size is an information, it should be in grey and right-aligned (see Software version in Settings)
* I'm not sure the text will fit if you want to display "32768o/32768o" in the different languages
* some unexpected characters are displayed if I press OK several times
I'm continuing to think about whether it's appropriate to display this information in the options menu.

**Comment by RedGl0w** [comment]
> I'm continuing to think about whether it's appropriate to display this information in the options menu.

When there was only 16Ko for Ion::Storage, it was very usefull... I think it's still usefull, and should be displayed here, or like https://github.com/numworks/epsilon/issues/1023 says, next to the file name... What do you think is best ?

**Comment by RedGl0w** [comment]
> I'm continuing to think about whether it's appropriate to display this information in the options menu.

If it shouldn't be displayed in the options menu, where would you like to see it ?

**Comment by RedGl0w** [comment]
Rebased : https://github.com/numworks/epsilon/pull/1487

**Pull request closed without merging**
