### PR TITLE
Fix metrics and screenshots in CI

### PR DESCRIPTION
**Pull request by FelixNumworks**

### CODE REVIEW

**Comment by FelixNumworks** [comment]
Test for this [here](https://github.com/numworks/epsilon/pull/2058)

**Comment by FelixNumworks** [comment]
CI of windos, android, macos and ios still not working

**Comment by AdnaneKhan** [comment]
Hello!

I came across this repository while scanning for CI/CD vulnerabilities on GitHub, and based on this workflow configuration it would be vulnerable to a malicious pull request that could modify repository code (https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). Don't merge this PR without addressing it!

The main branch code would be vulnerable but it being broken protects you, in a way :)

Make sure not to provide any write tokens to the repository when running externally controlled code with the `pull_request_target` trigger.

**Comment by FelixNumworks** [comment]
Thanks a lot for your help, we'll look into this.

**Pull request closed without merging**
