### PR TITLE
[python] Add `distance` function for Python turtle module 

### PR DESCRIPTION
**Pull request by Arthur-GYT**
> [!NOTE]
> Unconsciously, I deleted my fork, so I recreate my PR's 1 by 1... Sorry for the inconvenience...

All is in the title.

https://docs.python.org/3/library/turtle.html#turtle.distance

### CODE REVIEW

**Comment by FelixNumworks** [comment]
Thanks you for your contribution to the project :)
The product team has not decided yet if this change will be added to a future release of epsilon. I'll notify you when we know more.

**Comment by mobluse** [comment]
Scratch also has distance_to(), so it would help students who come from Scratch to Numworks Python: https://scratch.mit.edu/help/studio/tips/blocks/distance-to/

**Comment by mobluse** [comment]
Maybe
`float distance = sqrt(pow(x - sTurtle.x(), 2) + pow(y - sTurtle.y(), 2));`
would be faster as
`float distance = sqrt((x - sTurtle.x())*(x - sTurtle.x()) + (y - sTurtle.y())*(y - sTurtle.y()));`
or
```
float dx = x - sTurtle.x();
float dy = y - sTurtle.y();
float distance = sqrt(dx*dx + dy*dy);
```

**Comment by PiaNumworks** [comment]
Thank you for your contribution!
We cherry-picked your changes in our private repo to integrate them in the next version of epsilon.

**Pull request closed without merging**
