### PR TITLE
Repair windows build

### PR DESCRIPTION
**Pull request by EmilieNumworks**

### CODE REVIEW

**Comment by adriweb** [comment]
(typo: "repair", or just "fix")

@jacobly0 you might want to check this out, compared to [your windows branch](https://github.com/jacobly0/epsilon/tree/windows).

**Comment by adriweb** [comment]
Shall I suggest cmake? :P

**Comment by rhaamo** [comment]
CMake will clearly not be easier than Makefiles, also modularity won't be too.
Without talking about managing the build for device or emscripten or simulator or blackbox.

For detecting windows in Makefile it's possible to use something like this (https://stackoverflow.com/a/12099167):

```makefile
ifeq ($(OS),Windows_NT)
    #Windows stuff
    ...
else
    #Linux stuff whatever
    ....
endif
```

**Comment by adriweb** [comment]
BTW, on Windows, building works fine in WSL according to a reddit comment (however, I don't think the simulator has been launched in it, since it would require X11 or something)

**Comment by Ecco** [comment]
> Shall I suggest migrating to cmake?

You sure can, but we'd really need a compelling reason. I'm pretty sure GNU Make can do the job :)

**Comment by Ecco** [comment]
> BTW, on Windows, building works fine in WSL according to a reddit comment (however, I don't think the simulator has been launched in it, since it would require X11 or something)

That's good to know. The big upside of using mingw is that you can produce a binary that runs on any Windows computer, without any dependency. Which is definitely something that's useful :)

**Comment by Ecco** [comment]
> For detecting windows in Makefile it's possible to use something like this (https://stackoverflow.com/a/12099167)

Oh, that's a good find. Actually we could use it in `platform.simulator.mak` to automagically pick the mingw toolchain. Great suggestion, thanks @rhaamo :)

**Comment by Ecco** [comment]
Ok, let's merge this as-is for now, since it's a good first step anyway.

**Pull request merged**
