### PR TITLE
Move I18n file to specific folders for apps

### PR DESCRIPTION
**Pull request by Arthur-GYT**
> [!NOTE]
> Unconsciously, I deleted my fork, so I recreate my PR's 1 by 1... Sorry for the inconvenience...

All is in the title.

This is to standardize with the distribution app and it looks "cleaner".

### CODE REVIEW

**Comment by FelixNumworks** [comment]
Thanks you for your contribution to the project :)
Your commit was cherry-picked in our private repository and will be included in a future release of epsilon.

PS: Sorry for all these copy-paste, it's a bit unpersonnal I know. But really, thank you for your interest and contributions :)

**Comment by Arthur-GYT** [comment]
> Thanks you for your contribution to the project :)
> Your commit was cherry-picked in our private repository and will be included in a future release of epsilon.
> 
> PS: Sorry for all these copy-paste, it's a bit unpersonnal I know. But really, thank you for your interest and contributions :)

No problems ^^.

**Comment by Mysterious-Dev** [comment]
@FelixNumworks Now that 22.2.0 has been released, I don't see the restructuring done with this PR. Is this because it's planned for 22.3.x or 23.x.x?

**Comment by Arthur-GYT** [comment]
@FelixNumworks Now that 22.2.0 has been released, I don't see the restructuring done with this PR. Is this because it's planned for 22.3.x or 23.x.x?

**Comment by FelixNumworks** [comment]
Hello :) Yes it will be released in 23.0.0. We merged your PR after the end of the version 22 development process

**Comment by Arthur-GYT** [comment]
Nice ^^. Thanks for your answer ^^

**Pull request closed without merging**
