### PR TITLE
[apps] [i18n] Fix default language if not EN

### PR DESCRIPTION
**Pull request by adriweb**
When English was not built-in, this value wouldn't be available

### CODE REVIEW

**Comment by adriweb** [comment]
Note that I'm not sure the "Default" value is even needed anymore (just in case, I didn't touch it).
Also, the value "1" will always be defined anyway since using an empty list of languages in the build config will error beforehand

**Comment by vardai** [comment]
You should also join issue #673 to help fix localization further.

**Comment by adriweb** [comment]
Any update on that PR, by the way?
@Ecco @LeaNumworks @EmilieNumworks (not sure who to highlight :P)

**Comment by LeaNumworks** [comment]
Hi @adriweb, I am sorry we did not review this PR sooner.
Thanks for spotting the problem and for your PR. However, I did another PR (#1454), which I think handles the problem a little better:
- As you suspected, the Default value was useless so I got rid of it
- Instead of adding another Language value, I modified the i18n.py script, so that the first locale passed as a parameter has the value 0, and the default language is now 0.

Thanks again!

**Pull request closed without merging**
