### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

\apps\probability\images\focused_uniform_icon.png (99.73%))
\apps\exam_icon.png (39.82%))
\apps\probability\images\focused_exponential_icon.png (99.26%))
\apps\probability\images\focused_calcul4_icon.png (99.05%))
\apps\on_boarding\logo_icon.png (33.44%))
\apps\code\code_icon.png (11.4%))
\apps\probability\images\binomial_icon.png (99.58%))
\apps\probability\probability_icon.png (19.05%))
\apps\probability\images\calcul1_icon.png (99.04%))
\apps\calculation\calculation_icon.png (50.09%))
\apps\graph\graph_icon.png (33.33%))
\apps\probability\images\focused_poisson_icon.png (99.67%))
\apps\probability\images\focused_calcul2_icon.png (99.04%))
\apps\probability\images\calcul2_icon.png (99.01%))
\apps\probability\images\focused_normal_icon.png (99.08%))
\apps\probability\images\focused_calcul3_icon.png (99.04%))
\apps\probability\images\normal_icon.png (98.81%))
\apps\sequence\sequence_icon.png (50.06%))
\apps\probability\images\uniform_icon.png (99.64%))
\apps\probability\images\focused_binomial_icon.png (99.7%))
\apps\probability\images\calcul4_icon.png (98.97%))
\apps\statistics\stat_icon.png (31.11%))
\apps\probability\images\calcul3_icon.png (98.99%))
\apps\probability\images\exponential_icon.png (99.06%))
\apps\probability\images\poisson_icon.png (99.59%))
\apps\settings\settings_icon.png (43.8%))
\apps\regression\regression_icon.png (36.66%))
\apps\probability\images\focused_calcul1_icon.png (99.09%))

### CODE REVIEW

**Comment by adriweb** [comment]
Good idea @dabutvin (bot author), but now the image inliner can't process those images :P
`Error: Inliner only handles RGBA PNG images.make: *** [apps/calculation/calculation_icon.cpp] Error 255`
Probably doesn't implement all of the PNG spec/tricks to understand those correctly...

**Comment by dabutvin** [comment]
Interesting. I'd be curious to understand what exactly is happening here.
I opened an issue https://github.com/dabutvin/ImgBot/issues/20

I didn't even think about cla...

**Comment by boricj** [comment]
The Inliner is a simple in-tree tool to convert PNG files to raw C++ code. It's not quite smart enough to deal with sophisticated PNG files.

Furthermore, the images are stored raw and uncompressed in the firmware/executable outputs, so there would be no change at all for the end-user at the end.

**Comment by adriweb** [comment]
( See here for the inline core: https://github.com/numworks/epsilon/blob/master/escher/image/inliner.c )
About the images on device, here are some related thoughts for compression: https://github.com/numworks/epsilon/issues/33#issuecomment-326279133 + replies

**Comment by dabutvin** [comment]
That's really cool, thanks for the info.

**Pull request closed without merging**
