### PR TITLE
cppcheck: Resource leak: inputFile [resourceLeak]

### PR DESCRIPTION
**Pull request by serval2412**

### CODE REVIEW

**Comment by PiaNumworks** [comment]
Thank you for your contribution. We cherry-picked your changes in our private repo to integrate them in one of the next versions of epsilon.

**Comment by serval2412** [comment]
Thank you the merge!
Just for curiosity, when this will be included in https://github.com/numworks/epsilon ?
I mean, I suppose https://github.com/numworks/epsilon has different branches, eg : "master" is development one, then 1 branch per release.

**Comment by PiaNumworks** [comment]
Next version is already at a beta stage (you can see the beta version on our website), so your changes will not be included in this one. It will be included in the following one.
The code of each version is published in https://github.com/numworks/epsilon when the bêta version becomes stable.

**Comment by PiaNumworks** [comment]
> Thank you the merge!
> Just for curiosity, when this will be included in https://github.com/numworks/epsilon ?
> I mean, I suppose https://github.com/numworks/epsilon has different branches, eg : "master" is development one, then 1 branch per release.

Next version is already at a beta stage (you can see the beta version on our website), so your changes will not be included in this one. It will be included in the following one.
The code of each version is published in https://github.com/numworks/epsilon when the bêta version becomes stable.

**Pull request closed without merging**
