### PR TITLE
Compile time apps modularity, version 2

### PR DESCRIPTION
**Pull request by boricj**
Second version of #73, along with an updated "Hello, World!" sample at https://github.com/boricj/numworks-hello-world.

The main issue now is that there are lots of translations inside apps that are used in shared files, which is taken care of in `[apps] Extract shared translations from apps`.

### CODE REVIEW

**Comment by boricj** [comment]
I made another sample app (https://github.com/boricj/numworks-tic-tac-toe) to further demonstrate.

**Comment by adriweb** [comment]
Nice!
Considering the two manual commits are quite simple and that the 3rd is on auto-generated, I hope this gets merged :)

**Comment by debrouxl** [comment]
I hope that modularity remains a goal for Numworks, and as such, that this PR is merged ASAP :)

**Comment by Ecco** [comment]
Hi @boricj . Thank you very much for this PR, which we definitely **will** merge.

I'd like to apologize for not merging it before: it was conflicting with the upcoming Python app and we were on a tight schedule.

The biggest conflict is most likely the one from 3bca25c , but maybe simply removing this commit might work. As you can see, we (hopefully) fixed the `mp_hal_stdout_tx_strn_cooked` situation [once and for all](https://github.com/numworks/epsilon/blob/62899e8ebec9f3abddcdd6b3d8737c59f840c21d/python/port/port.cpp#L169).

**Comment by boricj** [comment]
This pull request has been rebased.

**Comment by Ecco** [comment]
Thank you very much @boricj, that is a very good PR! And thank you for rebasing!

**Comment by daniel-jozsef** [comment]
Nice! And you know what else this is good for? Allowing users to add separately distributed GPL licensed apps to their local build. ;) Especially once the Epsilon license is fixed ( #38 )...

**Pull request merged**
