### PR TITLE
Update German language file

### PR DESCRIPTION
**Pull request by FloMiau**
replace "Testmodus" with "Prüfungsmodus"
Real: "Reel" -> "Reell"
Gradians: "Gone" -> "Gon"

### CODE REVIEW

**Comment by EmilieNumworks** [comment]
Thanks @FloMiau! Good catches. I however can't merge this if you don't sign the CLA.

**Comment by FloMiau** [comment]
@EmilieNumworks done

**Comment by EmilieNumworks** [comment]
So quick! Thanks @FloMiau. However, there is still conflict with the master branch. Could you rebase your branch on top of it?

**Comment by EmilieNumworks** [comment]
Don't worry, I'll rebase your PR in another PR. I refer it when I'm done.

**Comment by EmilieNumworks** [comment]
See  #1469

**Pull request closed without merging**
