### PR TITLE
🐟

### PR DESCRIPTION
**Pull request by Ecco**
Maybe merging this isn't such a good idea 😄

### CODE REVIEW

**Comment by cent20net** [comment]
🐠

**Comment by M4xi1m3** [comment]
🐡 < I prefer that one

**Comment by quentinguidee** [comment]
🐳

**Comment by Ecco** [comment]
My inner geek *had* to give a thumbs up to the [pufferfish](https://www.openbsd.org/art1.html) 😄

**Comment by M4xi1m3** [comment]
Guess what, the puffer fish was actually chosen as a reference to openbsd.

**Comment by artaxxx** [comment]
Good point, we forgot this fish in the percolator

**Pull request closed without merging**
