### PR TITLE
[ion] [simulator] more realistic button labels

### PR DESCRIPTION
**Pull request by adriweb**
Looks like this now:

screenshot

### CODE REVIEW

**Comment by adriweb** [comment]
Updated with better arrows (thanks @jacobly0)

**Comment by Ecco** [comment]
That's a very nice addition, thank you so much!

That being said, I'm not comfortable using non-ASCII characters in the source code. I know it shouldn't be an issue with most toolchains, but this may end up triggering weird corner-case issues down the road.

Would you mind updating your patch to use Unicode escape codes (\uXXXX)?

**Comment by adriweb** [comment]
Alright, this should probably be fine (couldn't test right now though).

**Comment by Ecco** [comment]
Looks great. We fixed a typo on the CLA (a missing space…), so we would need you to sign it before we can merge this…

**Pull request merged**
