### PR TITLE
Added % in poincare

### PR DESCRIPTION
**Pull request by RedGl0w**
image

### CODE REVIEW

**Comment by Ecco** [comment]
I'm not a 100% sure we want to map `%` to the modulo operation. A lot of people use this symbol for actual percentages, and we've had request (even though not very clear) about supporting these…

**Comment by RedGl0w** [comment]
> 
> 
> I'm not a 100% sure we want to map `%` to the modulo operation. A lot of people use this symbol for actual percentages, and we've had request (even though not very clear) about supporting these…

Currently, my PR will output an error if someone does `50%` for exemple, so the main question to think is : will you add the percent as percent in the future or not. I don't think this is the better idea : in Python the percent is the modulo operator, and one of the main selling argument was the python support (and people want more compatibility between calculation / code), so I don't think creating this difference is a good idea...

**Comment by A2drien** [comment]
I think it would be better to display `3` instead of `8-5[8/5] = 3`.
I don't think if you do 5×7 you want to see `7+7+7+7+7 = 35`. 😉

**Comment by RedGl0w** [comment]
> I think it would be better to display `3` instead of `8-5[8/5] = 3`.
> I don't think if you do 5×7 you want to see `7+7+7+7+7 = 35`. wink

Yes, some people have already told me (ex : A2drien :trollface: )

**Comment by artaxxx** [comment]
I don't think we should use the percentage sign. It's very confusing. Doesn't that duplicate the `rem` function by the way?

**Comment by RedGl0w** [comment]
I didn't know there was the rem function. And I don't think personally that the % symbol is confusing for rem...

**Comment by RedGl0w** [comment]
Indeed, I think that neither the rem function nor % are perfect solution for that, but rem is a bit better. Closing

**Pull request closed without merging**
