### PR TITLE
Binary arithmetic functions

### PR DESCRIPTION
**Pull request by joecrop**
After a lengthy discussion and planing here: https://github.com/numworks/epsilon/issues/146, I have implemented binary arithmetic functions on integers. This PR contains the following new calculator/poincare functions:
```c++
static Integer xor(const Integer &a, const Integer &b, const Integer &num_bits = 32); // x = a ^ b
static Integer xnor(const Integer &a, const Integer &b, const Integer &num_bits = 32); // x = ~(a ^ b)
static Integer and(const Integer &a, const Integer &b, const Integer &num_bits = 32); // x = a & b
static Integer nand(const Integer &a, const Integer &b, const Integer &num_bits = 32); //x = ~(a & b)
static Integer or(const Integer &a, const Integer &b, const Integer &num_bits = 32); // x = a | b
static Integer nor(const Integer &a, const Integer &b, const Integer &num_bits = 32); // x = ~(a | b)
static Integer not(const Integer &a, const Integer &num_bits = 32); // x = ~a
static Integer sll(const Integer &a, const Integer &shift, const Integer &num_bits = 32); // x = a << shift, shift left logical
static Integer srl(const Integer &a, const Integer &shift, const Integer &num_bits = 32); // x = a >> shift, shift right logical
static Integer sra(const Integer &a, const Integer &shift, const Integer &num_bits = 32); // x = a >>> shift, shift right arithmetic
static Integer ror(const Integer &a, const Integer &rotate, const Integer &num_bits = 32); // x = (a >> shift) | ((a & 1) << num_bits), rotate right
static Integer rol(const Integer &a, const Integer &rotate, const Integer &num_bits = 32); // x = (a << shift) | (a & 1), rotate left
static Integer bic(const Integer &a, const Integer &b, const Integer &num_bits = 32); // x = (a & ~b)
static Integer bit(const Integer &a, const Integer &bit); // (a >> bit) & 1, return the bit-th bit of a
static Integer bclr(const Integer &a, const Integer &bit); // x = a & ~(1 << bit), clear tha bit-th bit of a;
static Integer bset(const Integer &a, const Integer &bit); // x = a | (1 << bit), clear tha bit-th bit of a;
static Integer bflp(const Integer &a, const Integer &bit); // x = a ^ (1 << bit), flip the bit-th bit of a.
```

### CODE REVIEW

**Comment by joecrop** [comment]
@debrouxl can you please review? Most of the Code is copy-paste, but there are two files that contain the key functionality and test cases:

1. poincare/src/integer.cpp
2. poincare/test/logic.cpp

**Comment by joecrop** [comment]
I don't understand how to fix the build failure messages in the CI logs:
```
/home/runner/work/epsilon/epsilon/head/poincare/include/poincare/nand.h:38: undefined reference to `Poincare::Evaluation<float> Poincare::NandNode::templatedApproximate<float>(Poincare::ExpressionNode::ApproximationContext) const'
```
I diff-ed these failing classes with the 'round' class and see very little differences that could be related to this error message.
Can someone point me in the right direction please? Why does it pass on linux, but not when building for n0110?

**Comment by adriweb** [comment]
Looks like you merged instead of rebasing :)

**Comment by joecrop** [comment]
I definitely typed: `git rebase origin/master`. So I'm not sure what's going on... I'll keep poking.

**Comment by joecrop** [comment]
A rebase is proving challenging so I found it to be much easier to just create a new branch with a reset history. I am closing this PR as it is replaced by my new branch here: https://github.com/numworks/epsilon/pull/1775

**Pull request closed without merging**
